version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reimplementation_development
      MYSQL_USER: dev
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./reimplementation-back-end
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: dev
      DATABASE_PASSWORD: root
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    ports:
      - "3002:3002"
    volumes:
      - ./reimplementation-back-end:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./reimplementation-front-end
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:80"
    volumes:
      - ./reimplementation-front-end:/app
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data: